[2025-10-08T22:46:18.266+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flujo_RAG_completo.classify_op_texts manual__2025-10-07T22:42:20+00:00 [queued]>
[2025-10-08T22:46:18.269+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flujo_RAG_completo.classify_op_texts manual__2025-10-07T22:42:20+00:00 [queued]>
[2025-10-08T22:46:18.270+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2025-10-08T22:46:18.273+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): classify_op_texts> on 2025-10-07 22:42:20+00:00
[2025-10-08T22:46:18.280+0000] {standard_task_runner.py:57} INFO - Started process 65475 to run task
[2025-10-08T22:46:18.283+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'flujo_RAG_completo', 'classify_op_texts', 'manual__2025-10-07T22:42:20+00:00', '--job-id', '347', '--raw', '--subdir', 'DAGS_FOLDER/Ingestion_pipeline.py', '--cfg-path', '/tmp/tmpq6vh9we4']
[2025-10-08T22:46:18.285+0000] {standard_task_runner.py:85} INFO - Job 347: Subtask classify_op_texts
[2025-10-08T22:46:18.309+0000] {task_command.py:415} INFO - Running <TaskInstance: flujo_RAG_completo.classify_op_texts manual__2025-10-07T22:42:20+00:00 [running]> on host 5586102090b0
[2025-10-08T22:46:18.344+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flujo_RAG_completo' AIRFLOW_CTX_TASK_ID='classify_op_texts' AIRFLOW_CTX_EXECUTION_DATE='2025-10-07T22:42:20+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-07T22:42:20+00:00'
[2025-10-08T22:46:22.674+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-10-08T22:46:26.793+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-10-08T22:46:32.506+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-10-08T22:46:37.074+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-10-08T22:46:47.730+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-10-08T22:46:57.364+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-10-08T22:46:59.981+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-10-08T22:47:02.411+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-10-08T22:47:05.374+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-10-08T22:47:09.672+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-10-08T22:47:14.175+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-10-08T22:47:17.680+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-10-08T22:47:21.631+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-10-08T22:47:25.238+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-10-08T22:47:29.032+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-10-08T22:47:33.444+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-10-08T22:47:34.020+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to success. Terminating instance.
[2025-10-08T22:47:34.033+0000] {process_utils.py:131} INFO - Sending 15 to group 65475. PIDs of all processes in the group: [65475]
[2025-10-08T22:47:34.034+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 65475
[2025-10-08T22:47:34.037+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-10-08T22:47:34.041+0000] {_base_client.py:1071} INFO - Retrying request to /chat/completions in 0.424232 seconds
[2025-10-08T22:47:39.690+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-10-08T22:47:45.010+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-10-08T22:47:56.494+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-10-08T22:48:01.729+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-10-08T22:48:04.215+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-10-08T22:48:09.812+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-10-08T22:48:13.880+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-10-08T22:48:17.484+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-10-08T22:48:20.842+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-10-08T22:48:24.792+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-10-08T22:48:28.518+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-10-08T22:48:31.308+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-10-08T22:48:34.071+0000] {process_utils.py:149} WARNING - process psutil.Process(pid=65475, name='airflow task ru', status='sleeping', started='22:46:18') did not respond to SIGTERM. Trying SIGKILL
[2025-10-08T22:48:34.075+0000] {process_utils.py:86} INFO - Sending the signal 9 to group 65475
[2025-10-08T22:48:34.105+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=65475, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='22:46:18') (65475) terminated with exit code -9
[2025-10-08T22:48:34.106+0000] {standard_task_runner.py:172} ERROR - Job 347 was killed before it finished (likely due to running out of memory)
