[2025-10-07T23:49:11.188+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flujo_RAG_completo.pinecone_upsert_op manual__2025-10-07T22:42:20+00:00 [queued]>
[2025-10-07T23:49:11.193+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flujo_RAG_completo.pinecone_upsert_op manual__2025-10-07T22:42:20+00:00 [queued]>
[2025-10-07T23:49:11.193+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2025-10-07T23:49:11.200+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): pinecone_upsert_op> on 2025-10-07 22:42:20+00:00
[2025-10-07T23:49:11.211+0000] {standard_task_runner.py:57} INFO - Started process 10006 to run task
[2025-10-07T23:49:11.216+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'flujo_RAG_completo', 'pinecone_upsert_op', 'manual__2025-10-07T22:42:20+00:00', '--job-id', '336', '--raw', '--subdir', 'DAGS_FOLDER/Ingestion_pipeline.py', '--cfg-path', '/tmp/tmpq97xmdog']
[2025-10-07T23:49:11.222+0000] {standard_task_runner.py:85} INFO - Job 336: Subtask pinecone_upsert_op
[2025-10-07T23:49:11.258+0000] {task_command.py:415} INFO - Running <TaskInstance: flujo_RAG_completo.pinecone_upsert_op manual__2025-10-07T22:42:20+00:00 [running]> on host 5586102090b0
[2025-10-07T23:49:11.308+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flujo_RAG_completo' AIRFLOW_CTX_TASK_ID='pinecone_upsert_op' AIRFLOW_CTX_EXECUTION_DATE='2025-10-07T22:42:20+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-07T22:42:20+00:00'
[2025-10-07T23:49:11.312+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-10-07T23:49:11.313+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-07T23:49:11.313+0000] {warnings.py:109} WARNING - <string>:8: AirflowProviderDeprecationWarning: AWS Connection (conn_id='minio_s3', conn_type='s3') has connection type 's3', which has been replaced by connection type 'aws'. Please update your connection to have `conn_type='aws'`.

[2025-10-07T23:49:11.314+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-07T23:49:11.314+0000] {warnings.py:109} WARNING - <string>:8: AirflowProviderDeprecationWarning: Host minio specified in the connection is not used. Please, set it on extra['endpoint_url'] instead

[2025-10-07T23:49:11.597+0000] {logging_mixin.py:151} INFO - [PC/OP] ndjson_files=6 prefix=rag/chunks_op/2025/
[2025-10-07T23:49:11.598+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-07T23:49:11.598+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-07T23:49:11.905+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-07T23:49:11.906+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-07T23:49:11.956+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-07T23:49:11.956+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-07T23:49:12.019+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-07T23:49:12.020+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-07T23:49:12.074+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-07T23:49:12.074+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-07T23:49:12.145+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-07T23:49:12.145+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-07T23:49:12.213+0000] {logging_mixin.py:151} INFO - [PC/OP] parsed_kept=802 (tras min_chars>=20)
[2025-10-07T23:49:12.215+0000] {SentenceTransformer.py:208} INFO - Use pytorch device_name: cpu
[2025-10-07T23:49:12.215+0000] {SentenceTransformer.py:216} INFO - Load pretrained SentenceTransformer: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
[2025-10-07T23:49:38.825+0000] {logging_mixin.py:151} INFO - [PC/OP] embedding model=sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2 dim=384 total_vectors=802
[2025-10-07T23:49:38.828+0000] {discover_namespace_packages.py:12} INFO - Discovering subpackages in _NamespacePath(['/home/***/.local/lib/python3.8/site-packages/pinecone_plugins'])
[2025-10-07T23:49:38.829+0000] {discover_plugins.py:9} INFO - Looking for plugins in pinecone_plugins.inference
[2025-10-07T23:49:38.840+0000] {installation.py:10} INFO - Installing plugin inference into Pinecone
[2025-10-07T23:49:39.983+0000] {discover_namespace_packages.py:12} INFO - Discovering subpackages in _NamespacePath(['/home/***/.local/lib/python3.8/site-packages/pinecone_plugins'])
[2025-10-07T23:49:39.985+0000] {discover_plugins.py:9} INFO - Looking for plugins in pinecone_plugins.inference
[2025-10-07T23:49:39.986+0000] {installation.py:10} INFO - Installing plugin inference into Pinecone
[2025-10-07T23:49:47.222+0000] {logging_mixin.py:151} INFO - ✅ Upsert Pinecone (OP): indexed=802, dim=384, ns=2025
[2025-10-07T23:49:47.227+0000] {logging_mixin.py:151} INFO - ✅ Upsert Pinecone (OP): {'indexed': 802, 'dim': 384, 'namespace': '2025'}
[2025-10-07T23:49:47.228+0000] {python.py:194} INFO - Done. Returned value was: {'indexed': 802, 'dim': 384, 'namespace': '2025'}
[2025-10-07T23:49:47.246+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=flujo_RAG_completo, task_id=pinecone_upsert_op, execution_date=20251007T224220, start_date=20251007T234911, end_date=20251007T234947
[2025-10-07T23:49:47.316+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-10-07T23:49:47.326+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
