[2025-10-07T02:09:22.343+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flujo_RAG_completo.extract_texts manual__2025-10-07T02:08:37+00:00 [queued]>
[2025-10-07T02:09:22.347+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flujo_RAG_completo.extract_texts manual__2025-10-07T02:08:37+00:00 [queued]>
[2025-10-07T02:09:22.347+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-10-07T02:09:22.353+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract_texts> on 2025-10-07 02:08:37+00:00
[2025-10-07T02:09:22.359+0000] {standard_task_runner.py:57} INFO - Started process 16396 to run task
[2025-10-07T02:09:22.362+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'flujo_RAG_completo', 'extract_texts', 'manual__2025-10-07T02:08:37+00:00', '--job-id', '298', '--raw', '--subdir', 'DAGS_FOLDER/Ingestion_pipeline.py', '--cfg-path', '/tmp/tmpdhox587i']
[2025-10-07T02:09:22.365+0000] {standard_task_runner.py:85} INFO - Job 298: Subtask extract_texts
[2025-10-07T02:09:22.394+0000] {task_command.py:415} INFO - Running <TaskInstance: flujo_RAG_completo.extract_texts manual__2025-10-07T02:08:37+00:00 [running]> on host a21c1baf7ef9
[2025-10-07T02:09:22.436+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flujo_RAG_completo' AIRFLOW_CTX_TASK_ID='extract_texts' AIRFLOW_CTX_EXECUTION_DATE='2025-10-07T02:08:37+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-07T02:08:37+00:00'
[2025-10-07T02:09:22.437+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-10-07T02:09:22.438+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-07T02:09:22.439+0000] {warnings.py:109} WARNING - <string>:8: AirflowProviderDeprecationWarning: AWS Connection (conn_id='minio_s3', conn_type='s3') has connection type 's3', which has been replaced by connection type 'aws'. Please update your connection to have `conn_type='aws'`.

[2025-10-07T02:09:22.439+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-07T02:09:22.439+0000] {warnings.py:109} WARNING - <string>:8: AirflowProviderDeprecationWarning: Host minio specified in the connection is not used. Please, set it on extra['endpoint_url'] instead

[2025-10-07T02:09:22.636+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-07T02:09:22.637+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-07T02:09:28.083+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-07T02:09:28.085+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-07T02:09:28.452+0000] {logging_mixin.py:151} INFO - ✅ TXT subido: s3://respaldo2/rag/text/2025/22032_2025-09-16.txt  (páginas=70, chars=183179)
[2025-10-07T02:09:28.452+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-07T02:09:28.453+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-07T02:09:33.044+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-07T02:09:33.045+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-07T02:09:33.106+0000] {logging_mixin.py:151} INFO - ✅ TXT subido: s3://respaldo2/rag/text/2025/22033_2025-09-17.txt  (páginas=74, chars=183414)
[2025-10-07T02:09:33.106+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-07T02:09:33.107+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-07T02:09:37.464+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to upstream_failed. Terminating instance.
[2025-10-07T02:09:37.465+0000] {process_utils.py:131} INFO - Sending 15 to group 16396. PIDs of all processes in the group: [16396]
[2025-10-07T02:09:37.465+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 16396
[2025-10-07T02:09:37.465+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-10-07T02:09:37.521+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=16396, status='terminated', exitcode=0, started='02:09:22') (16396) terminated with exit code 0
