[2025-10-07T22:41:08.805+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flujo_RAG_completo.descargar_boletines_salta manual__2025-10-07T22:41:02+00:00 [queued]>
[2025-10-07T22:41:08.810+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flujo_RAG_completo.descargar_boletines_salta manual__2025-10-07T22:41:02+00:00 [queued]>
[2025-10-07T22:41:08.811+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-10-07T22:41:08.817+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): descargar_boletines_salta> on 2025-10-07 22:41:02+00:00
[2025-10-07T22:41:08.825+0000] {standard_task_runner.py:57} INFO - Started process 5669 to run task
[2025-10-07T22:41:08.831+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'flujo_RAG_completo', 'descargar_boletines_salta', 'manual__2025-10-07T22:41:02+00:00', '--job-id', '328', '--raw', '--subdir', 'DAGS_FOLDER/Ingestion_pipeline.py', '--cfg-path', '/tmp/tmpc3wvg0qy']
[2025-10-07T22:41:08.834+0000] {standard_task_runner.py:85} INFO - Job 328: Subtask descargar_boletines_salta
[2025-10-07T22:41:08.866+0000] {task_command.py:415} INFO - Running <TaskInstance: flujo_RAG_completo.descargar_boletines_salta manual__2025-10-07T22:41:02+00:00 [running]> on host 5586102090b0
[2025-10-07T22:41:08.909+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flujo_RAG_completo' AIRFLOW_CTX_TASK_ID='descargar_boletines_salta' AIRFLOW_CTX_EXECUTION_DATE='2025-10-07T22:41:02+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-07T22:41:02+00:00'
[2025-10-07T22:42:19.379+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-10-07T22:42:19.383+0000] {process_utils.py:131} INFO - Sending 15 to group 5669. PIDs of all processes in the group: [5669]
[2025-10-07T22:42:19.384+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 5669
[2025-10-07T22:42:19.385+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-10-07T22:43:19.413+0000] {process_utils.py:149} WARNING - process psutil.Process(pid=5669, name='airflow task ru', status='sleeping', started='22:41:08') did not respond to SIGTERM. Trying SIGKILL
[2025-10-07T22:43:19.427+0000] {process_utils.py:86} INFO - Sending the signal 9 to group 5669
[2025-10-07T22:43:19.455+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=5669, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='22:41:08') (5669) terminated with exit code -9
[2025-10-07T22:43:19.456+0000] {standard_task_runner.py:172} ERROR - Job 328 was killed before it finished (likely due to running out of memory)
